services:
  - type: web
    name: albumer
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx prisma migrate deploy && npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        fromDatabase:
          name: albumer-db
          property: connectionString
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_DRIVE_PARENT_ID
        sync: false

databases:
  - name: albumer-db
    plan: free
